<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nomor Rekening Anda 370-3-0011594-0</name>
   <tag></tag>
   <elementGuidId>38c4c959-61da-4311-a2d4-e5028d6eaaca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:ax:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Nomor Rekening Anda 370-3-0011594-0&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0e0b4c89-8601-474d-a519-795891917a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>55263ab2-41e3-4ae2-a9a4-a12e7e8f527a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Div:ax:</value>
      <webElementGuid>4bd84976-5692-4586-9f81-c84f54c54caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-div xui-uicontainer  xui-ui-ctrl xui-ui-selectable      xui-custom</value>
      <webElementGuid>342fe6ef-9ee0-46a1-95a5-0c3c8364fae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomor Rekening Anda 370-3-0011594-0</value>
      <webElementGuid>74a7d629-9636-4c55-8e5f-68ee36e91afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:ax:&quot;)</value>
      <webElementGuid>4c2442c5-d496-4803-aa85-ee13877120eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:ax:']</value>
      <webElementGuid>1ca087e1-88b8-4031-b7a7-8af328589940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Dialog-PANEL:i:']/div[2]</value>
      <webElementGuid>f9bfdc20-b409-4187-827b-ac832b2a3396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O K'])[1]/following::div[1]</value>
      <webElementGuid>c7bb9cde-6119-4a1c-a45e-63edf9eb0172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi'])[2]/following::div[8]</value>
      <webElementGuid>8787b990-3a54-4c9e-9738-a009d719cf9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nomor Rekening Anda 370-3-0011594-0']/parent::*</value>
      <webElementGuid>9605f56c-bbdf-4f9a-80c0-fcfd0fec23b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[18]/span/span/div[2]/div/div/div[2]</value>
      <webElementGuid>651191d6-c551-41b5-ad24-28635585da9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Div:ax:' and (text() = 'Nomor Rekening Anda 370-3-0011594-0' or . = 'Nomor Rekening Anda 370-3-0011594-0')]</value>
      <webElementGuid>1ccd3fb8-b5e6-4e3a-b155-8786b3b6dcdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
