<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create New Favorite_xui_j</name>
   <tag></tag>
   <elementGuidId>73db567b-4925-4e9b-88b1-79801217b7a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#xui_j</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui_j']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#xui_j</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6cf9a1ff-7a67-4e99-a76a-301dc5e0bcd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-cover xui-custom xui-cover-modal xui-ui-unselectable</value>
      <webElementGuid>f1cb783b-012c-4c65-a681-4bec57ae5d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui_j</value>
      <webElementGuid>9b7813e3-6c2b-4d61-b8e9-7a067be11cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui_j&quot;)</value>
      <webElementGuid>361c7346-e5a9-4779-b4e7-c2a0af1004ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui_j']</value>
      <webElementGuid>d8a85ae1-9a96-4f8d-9e91-48d80fed7233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='xui_a']/div[6]</value>
      <webElementGuid>1849e004-90ad-4a66-a396-28b2e353344f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>e75a7c90-cdf0-46c1-8774-9f06630fa216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui_j']</value>
      <webElementGuid>afbd636d-e9e8-4c23-a3c2-54370657d144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
