<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>f3da2500-e470-4522-a333-95f966db735f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.TreeGrid-CELLCAPTION:b:-c_e']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;xui\.UI\.TreeGrid-CELLCAPTION\:b\:-c_e&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8a6f379d-7213-475d-862b-5bdd0e1ace80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-CELLCAPTION:b:-c_e</value>
      <webElementGuid>6b2f6892-63f6-4771-a10d-48cc64cfdb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-treegrid-cellcaption xui-v-node     xui-custom</value>
      <webElementGuid>76c2d4a6-9070-4357-9a27-bf093fb8e823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a200ef15-f30c-471e-b87e-658ab4cf8bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-CELLCAPTION:b:-c_e&quot;)</value>
      <webElementGuid>1c8d0dc3-8b7a-47c2-8c9d-6c5d4ee7ca0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-CELLCAPTION:b:-c_e']</value>
      <webElementGuid>ab4bad4a-fd50-4623-ad40-30345fbe65ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-CELLA:b:-c_e']/span</value>
      <webElementGuid>9250befb-3e9e-45da-9f06-ba8158ba4340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibuat Oleh'])[2]/following::span[98]</value>
      <webElementGuid>35468b27-c786-4d75-bc21-eb44eebd170a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waktu Dibuat'])[2]/following::span[102]</value>
      <webElementGuid>1ea1bb22-a479-45d8-82d3-b7fdac353077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAPUS'])[4]/preceding::span[1]</value>
      <webElementGuid>6be74517-d7c8-46f6-a3cd-18c7f2c61116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERORANGAN'])[4]/preceding::span[7]</value>
      <webElementGuid>db2a0c84-6c99-427d-9e28-3feb59f133b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/div[2]/div/div/table/tbody/tr[3]/td[2]/div/div/div/div/div/span[5]/span/span</value>
      <webElementGuid>41e87446-d32d-48eb-b5cb-eae04e1faa33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.TreeGrid-CELLCAPTION:b:-c_e' and (text() = '1' or . = '1')]</value>
      <webElementGuid>55cdbd61-60e1-441c-a2a2-af018f4131d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
