<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilihan Printer_xui.UI.StatusButtons-C_698896</name>
   <tag></tag>
   <elementGuidId>4a28452c-a2c5-4854-9092-ec942bee6e75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.StatusButtons-CAPTION:e:a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cf18a811-b884-4463-a9c0-39f38f4ed41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.StatusButtons-CAPTION:e:a</value>
      <webElementGuid>81a1b5b4-221f-4c99-b578-54cd3b1b900e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-statusbuttons-caption     xui-custom</value>
      <webElementGuid>04a1a8e0-2af5-42f9-bbe9-16a497a54554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tidak</value>
      <webElementGuid>cbd9cf0a-9cb3-48be-90b8-3aa046a0ca91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.StatusButtons-CAPTION:e:a&quot;)</value>
      <webElementGuid>755512b9-e73d-484b-a0b5-e09401d327fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.StatusButtons-CAPTION:e:a']</value>
      <webElementGuid>bdeb0a34-74c7-4adb-97f6-64d7c60bac98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.StatusButtons-ITEM:e:a']/span[3]</value>
      <webElementGuid>d9db2514-cc3f-4821-8b23-f78d7a2c5ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilihan Printer'])[1]/following::span[9]</value>
      <webElementGuid>5dc6198d-1780-4dfa-a086-d5759479485c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak Slip ?'])[1]/following::span[15]</value>
      <webElementGuid>2e85c508-4ddb-4fc2-8a6b-156dce80efb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak'])[1]/preceding::span[6]</value>
      <webElementGuid>8014d2cd-8142-4ff7-ba18-d3a8823152bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::span[13]</value>
      <webElementGuid>b7aa04fd-d498-437e-bca7-b299c481284b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tidak']/parent::*</value>
      <webElementGuid>6c32a137-7bbd-4bfa-9a31-95385452796e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/span/span[3]</value>
      <webElementGuid>62978996-01db-47e6-8aff-849177c96878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.StatusButtons-CAPTION:e:a' and (text() = 'Tidak' or . = 'Tidak')]</value>
      <webElementGuid>7f4041d0-e658-4293-800d-b7b9860f6ee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
