<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TC - TAB HOGIKU_xui.UI.List-CAPTIONeu</name>
   <tag></tag>
   <elementGuidId>c40bea0e-d3e8-426f-93e7-8abf83f49dcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.List-CAPTION:e:u']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>431fd7ab-7e15-4b24-8539-68f51b99ae9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.List-CAPTION:e:u</value>
      <webElementGuid>3729fb0c-69c6-4f5e-9f04-1f52e67d7725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-list-caption     xui-custom</value>
      <webElementGuid>7cd3ed2f-99d5-435b-a1e3-fdff5c749f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TD - TABUNGANKU</value>
      <webElementGuid>5f0cf51a-17af-4f36-aae6-6f1764c5b958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.List-CAPTION:e:u&quot;)</value>
      <webElementGuid>6ae18684-7d79-4457-943e-31304dba5eec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.List-CAPTION:e:u']</value>
      <webElementGuid>c0444de6-7dac-4b75-86d6-b6c761a300ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.List-ITEM:e:u']/span[4]</value>
      <webElementGuid>fb70d691-3aa9-4699-b840-115d0f162625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TC - TAB HOGIKU'])[1]/following::span[8]</value>
      <webElementGuid>795c7c2b-cd7b-4af6-8776-baf10303c1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TB - TAB UMUM'])[1]/following::span[16]</value>
      <webElementGuid>b7b1b8fd-1754-4d27-9028-556b0ac2fbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TF - TABUNGAN SIKADO'])[1]/preceding::span[7]</value>
      <webElementGuid>96cb17aa-4757-4569-b2e0-a9e65dc0abb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TG - TABUNGAN SIMPEL'])[1]/preceding::span[15]</value>
      <webElementGuid>faeafe97-73ff-48cd-870a-f36e1d83ce99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TD - TABUNGANKU']/parent::*</value>
      <webElementGuid>b9839c8b-a100-428d-969b-ad4a70ea09f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span[21]/span[4]</value>
      <webElementGuid>81b89572-021a-4b15-afbd-8b031a17aef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.List-CAPTION:e:u' and (text() = 'TD - TABUNGANKU' or . = 'TD - TABUNGANKU')]</value>
      <webElementGuid>6ab9f355-6202-4399-baca-aeaa50e3c7de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
