<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TOTAL DANA_xui.UI.TreeGrid-HCELLAg</name>
   <tag></tag>
   <elementGuidId>75c8f411-4d37-41bb-a1ce-331650568e41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.TreeGrid-HCELLA:g:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d2cda037-0ef0-4052-ae72-514d96bd2142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-HCELLA:g:</value>
      <webElementGuid>9635274d-f596-49f3-8252-7810f37ec77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-treegrid-hcella xui-v-wrapper xui-showfocus      xui-custom</value>
      <webElementGuid>d97601df-4db7-43fc-b032-b442c2780677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-HCELLA:g:&quot;)</value>
      <webElementGuid>05309fd9-2c4c-48d7-9294-05e4e5894939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-HCELLA:g:']</value>
      <webElementGuid>79d93a2a-fe61-4896-8570-27402afaf965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-FHCELL:g:']/span</value>
      <webElementGuid>85762c5d-84d8-4592-967a-5151b8d03e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL DANA'])[1]/following::span[29]</value>
      <webElementGuid>6f423ff2-b5f1-4662-901a-fd4f5b9d4678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SETOR TUNAI 370100059841 A/N HUBERTUS KENNETH'])[1]/following::span[50]</value>
      <webElementGuid>e9cf80b7-2f6b-4d8d-9fb3-be7767a0af01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/preceding::span[6]</value>
      <webElementGuid>f8cdc593-85b1-4632-b080-098c932d971d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode'])[1]/preceding::span[10]</value>
      <webElementGuid>d9e97842-f0b5-453b-9aa1-30cad8b4cc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/table/tbody/tr/td/div/div/div/span/span</value>
      <webElementGuid>ec2cf1c1-467b-4b34-a846-15f3ce220283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.TreeGrid-HCELLA:g:']</value>
      <webElementGuid>6505c071-66c3-46ee-a0b8-fb4a363cd5d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
