<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_INFORMASI_xlid (1)</name>
   <tag></tag>
   <elementGuidId>a697ceab-b2a8-49e5-bcdb-766b15f5d9d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='xlid'])[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>106746b0-9091-488f-8448-d1072c3dfd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xlid</value>
      <webElementGuid>a2ae414b-d379-4607-8dd5-b96ee2366a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline.ok</value>
      <webElementGuid>1333a366-4ec7-47af-a1b7-78da748a360b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>O K</value>
      <webElementGuid>72e6ebe7-b100-4ca2-bb25-f070cc56615d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Button-CAPTION:ai:&quot;)/span[@id=&quot;xlid&quot;]</value>
      <webElementGuid>cc5b8aec-ccb5-4fb9-8b65-51d36c1a821a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='xlid'])[20]</value>
      <webElementGuid>d811a578-21a0-4b50-b7f6-8494dc6dd9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Button-CAPTION:ai:']/span</value>
      <webElementGuid>3e4b414a-7edb-4bf4-b75f-2a9361a31812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INFORMASI'])[2]/following::span[13]</value>
      <webElementGuid>7b3e374c-6873-444b-ba20-7bc3570b8a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Favorite'])[1]/following::span[29]</value>
      <webElementGuid>9f7acfc6-a710-45c0-8dd6-8cc2b2a904fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[SC0001] Berhasil simpan data.'])[1]/preceding::span[2]</value>
      <webElementGuid>c2aba758-01a4-42c8-a45f-481cff1eb125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='O K']/parent::*</value>
      <webElementGuid>30c811b9-c49f-40d5-9f5a-4cea5cfca944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]/span</value>
      <webElementGuid>e96ede84-c345-438c-95da-ec59053a4c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xlid' and (text() = 'O K' or . = 'O K')]</value>
      <webElementGuid>8af87083-cb84-478e-b1a3-a4eb764ffdd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
