<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TRANSAKSI UMUM_xui.UI.Divt</name>
   <tag></tag>
   <elementGuidId>cbda0b48-3089-4cfd-a9c3-f10b959b3d6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:t:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2851ff21-f6d5-4ad4-bdb2-6c8d4d232264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>ac4b2e87-96f7-4e85-9b14-47615c5afc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Div:t:</value>
      <webElementGuid>6987ad44-63ab-4462-b7a0-ad7c29be8ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-div xui-uicontainer xui-ui-ctrl xui-ui-selectable xui-custom xui-css-noscrollx</value>
      <webElementGuid>1e60ec4d-fd11-42d3-bfd3-e6b7308479fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>idPilih Transaksi*Nomor Slip**TRANSAKSI UMUMPelaku Transaksi*No Identitas**Nama**No Handphone**Narasi untuk Seluruh RekeningDATA REKENINGNama Pemilik RekeningNomor Rekening*Nomor Rekening*Kalkulasi SetoranNominal*NarasiSetoran PokokSetoran BungaSetoran DendaSetoran PenaltiTotal SetoranSubmitNoNo RekeningPokokBungaDendaPenaltiTotal NominalNarasicif_idstatusfullnmcurrency_idbrncdid BatalSimpanNoTanggal Bayar BungaNominalid Nasabah Pemilik RekeningNoNama NasabahIdentitasTTDslideIndeximg DAFTAR NASABAHSurat Kuasa RekeningNoNoNama NasabahIdentitasMasa Berlaku IDKuasaMasa Berlaku SKTTDslideIndeximg DAFTAR KUASATanda Tangan Diragukan?YaBatalSimpanSaldo Tersedia10.000.000,00Nomor Rekening*Nomor Rekening**Nominal*NarasiPelaku Transaksi*No Identitas**Nama**No Handphone**DATA REKENINGNo LikuidasiNama Pemilik RekeningNoNo RekeningCRDRPokokBungaDendaPenaltiTotal NominalNarasicif_idstatusfullnmcurrency_idbrncdidid TOTAL DEBET :TOTAL KREDIT :DATA REKENINGNama Pemilik RekeningNomor Rekening*Nomor Rekening*Saldo Tersedia10.000.000,00Nominal*Debet/Kredit*Kalkulasi SetoranNo LikuidasiNoTanggal Bayar BungaNominalid NarasiSetoran PokokSetoran BungaSetoran DendaSetoran PenaltiTotal SetoranSubmitNasabah Pemilik RekeningNoNoNama NasabahIdentitasTTDslideIndeximg DAFTAR NASABAHRekening Debet*Surat Kuasa RekeningNoNoNama NasabahIdentitasMasa Berlaku IDKuasaMasa Berlaku SKTTDslideIndeximg DAFTAR KUASARekening Debet*Tanda Tangan Diragukan?YaBatalSimpanNarasi untuk Seluruh RekeningTanggal EfektifPelaku Transaksi*No Identitas**Nama**No Handphone**BatalSimpan</value>
      <webElementGuid>06ae8fdb-b975-4cf8-b57c-d77932d92f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:t:&quot;)</value>
      <webElementGuid>ba935487-d41e-4863-80a8-07af21e5f84c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:t:']</value>
      <webElementGuid>ba309728-1771-412c-8139-58ac1b31aadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Block-PANEL:r:']/div</value>
      <webElementGuid>227e33fa-c89b-42e7-9084-c83ea995a3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI UMUM'])[1]/following::div[8]</value>
      <webElementGuid>ba8ae33c-aab7-4101-be39-99a2cd653c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='c'])[1]/following::div[11]</value>
      <webElementGuid>674adecf-34ed-4089-ae22-957935bd4996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/span/span/div[2]/div</value>
      <webElementGuid>99c8f26e-eaff-4a13-ac66-310f01824839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Div:t:' and (text() = 'idPilih Transaksi*Nomor Slip**TRANSAKSI UMUMPelaku Transaksi*No Identitas**Nama**No Handphone**Narasi untuk Seluruh RekeningDATA REKENINGNama Pemilik RekeningNomor Rekening*Nomor Rekening*Kalkulasi SetoranNominal*NarasiSetoran PokokSetoran BungaSetoran DendaSetoran PenaltiTotal SetoranSubmitNoNo RekeningPokokBungaDendaPenaltiTotal NominalNarasicif_idstatusfullnmcurrency_idbrncdid BatalSimpanNoTanggal Bayar BungaNominalid Nasabah Pemilik RekeningNoNama NasabahIdentitasTTDslideIndeximg DAFTAR NASABAHSurat Kuasa RekeningNoNoNama NasabahIdentitasMasa Berlaku IDKuasaMasa Berlaku SKTTDslideIndeximg DAFTAR KUASATanda Tangan Diragukan?YaBatalSimpanSaldo Tersedia10.000.000,00Nomor Rekening*Nomor Rekening**Nominal*NarasiPelaku Transaksi*No Identitas**Nama**No Handphone**DATA REKENINGNo LikuidasiNama Pemilik RekeningNoNo RekeningCRDRPokokBungaDendaPenaltiTotal NominalNarasicif_idstatusfullnmcurrency_idbrncdidid TOTAL DEBET :TOTAL KREDIT :DATA REKENINGNama Pemilik RekeningNomor Rekening*Nomor Rekening*Saldo Tersedia10.000.000,00Nominal*Debet/Kredit*Kalkulasi SetoranNo LikuidasiNoTanggal Bayar BungaNominalid NarasiSetoran PokokSetoran BungaSetoran DendaSetoran PenaltiTotal SetoranSubmitNasabah Pemilik RekeningNoNoNama NasabahIdentitasTTDslideIndeximg DAFTAR NASABAHRekening Debet*Surat Kuasa RekeningNoNoNama NasabahIdentitasMasa Berlaku IDKuasaMasa Berlaku SKTTDslideIndeximg DAFTAR KUASARekening Debet*Tanda Tangan Diragukan?YaBatalSimpanNarasi untuk Seluruh RekeningTanggal EfektifPelaku Transaksi*No Identitas**Nama**No Handphone**BatalSimpan' or . = 'idPilih Transaksi*Nomor Slip**TRANSAKSI UMUMPelaku Transaksi*No Identitas**Nama**No Handphone**Narasi untuk Seluruh RekeningDATA REKENINGNama Pemilik RekeningNomor Rekening*Nomor Rekening*Kalkulasi SetoranNominal*NarasiSetoran PokokSetoran BungaSetoran DendaSetoran PenaltiTotal SetoranSubmitNoNo RekeningPokokBungaDendaPenaltiTotal NominalNarasicif_idstatusfullnmcurrency_idbrncdid BatalSimpanNoTanggal Bayar BungaNominalid Nasabah Pemilik RekeningNoNama NasabahIdentitasTTDslideIndeximg DAFTAR NASABAHSurat Kuasa RekeningNoNoNama NasabahIdentitasMasa Berlaku IDKuasaMasa Berlaku SKTTDslideIndeximg DAFTAR KUASATanda Tangan Diragukan?YaBatalSimpanSaldo Tersedia10.000.000,00Nomor Rekening*Nomor Rekening**Nominal*NarasiPelaku Transaksi*No Identitas**Nama**No Handphone**DATA REKENINGNo LikuidasiNama Pemilik RekeningNoNo RekeningCRDRPokokBungaDendaPenaltiTotal NominalNarasicif_idstatusfullnmcurrency_idbrncdidid TOTAL DEBET :TOTAL KREDIT :DATA REKENINGNama Pemilik RekeningNomor Rekening*Nomor Rekening*Saldo Tersedia10.000.000,00Nominal*Debet/Kredit*Kalkulasi SetoranNo LikuidasiNoTanggal Bayar BungaNominalid NarasiSetoran PokokSetoran BungaSetoran DendaSetoran PenaltiTotal SetoranSubmitNasabah Pemilik RekeningNoNoNama NasabahIdentitasTTDslideIndeximg DAFTAR NASABAHRekening Debet*Surat Kuasa RekeningNoNoNama NasabahIdentitasMasa Berlaku IDKuasaMasa Berlaku SKTTDslideIndeximg DAFTAR KUASARekening Debet*Tanda Tangan Diragukan?YaBatalSimpanNarasi untuk Seluruh RekeningTanggal EfektifPelaku Transaksi*No Identitas**Nama**No Handphone**BatalSimpan')]</value>
      <webElementGuid>7452bcb3-6674-4097-bb21-912f78a84cc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
