<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PARAMETER WEWENANG TRANSAKSI_xui.UI.Divaz</name>
   <tag></tag>
   <elementGuidId>87aa4a3f-15c6-49cc-9773-7b13fe8ab9dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:az:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f6eedec6-7c19-4db7-86e5-81a1369ebf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>47d5b3f9-adbb-4137-8205-1b3e57204078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Div:az:</value>
      <webElementGuid>6c812bcc-833f-4868-8374-92093617491f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-div xui-uicontainer xui-ui-ctrl xui-ui-selectable xui-custom xui-css-noscrollx</value>
      <webElementGuid>9ddef360-3365-4b2d-affd-06bfa46cbe6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PARAMETER WEWENANG TRANSAKSIPencarianTampilUrut BerdasarkanNoDepartemenLevelKhusus UserStatusididt10001 - DIREKTUR UTAMA1 - DIREKTUR UTAMAAKTIF425000 - TEAM SINERGI0 - KOMISARISAKTIF635000 - TEAM SINERGI7 - KEPALA UNITAKTIF545000 - TEAM SINERGI8 - PELAKSANAAKTIF755000 - TEAM SINERGI5 - MANAGERSALTEL2AKTIF869110 - SIE FRONT OFFICE/TELLER8 - PELAKSANAAKTIF179110 - SIE FRONT OFFICE/TELLER7 - KEPALA UNITAKTIF289120 - SIE AKUNTANSI8 - PELAKSANAAKTIF399151 - TELLER KANTOR KAS8 - PELAKSANAAKTIF9 DATA PARAMETER WEWENANG TRANSAKSIDepartemen*Level*Khusus UserWewenang Transaksi*idtHapusSimpanBatalcolumn_idlastupukey1....02....1</value>
      <webElementGuid>eaac93c4-7e97-45ac-bd7d-f50481ea237b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:az:&quot;)</value>
      <webElementGuid>534c8aba-2975-465d-8581-d6bd9ca572d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:az:']</value>
      <webElementGuid>778f3cd9-6707-4dcc-b499-127b32ffb33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Block-PANEL:s:']/div</value>
      <webElementGuid>4b7fb50e-d9a1-4e26-81e2-58aec24d0df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PARAMETER WEWENANG TRANSAKSI'])[1]/following::div[8]</value>
      <webElementGuid>cec6e4b5-b854-4681-b4b2-d0708b22bcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[4]/following::div[11]</value>
      <webElementGuid>2ffbed95-b79e-4c4d-831b-f5331056f522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/div[2]/div/div/span/span/span/div[2]/div</value>
      <webElementGuid>8dbf0be7-a51b-4283-9222-d99500125fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Div:az:' and (text() = 'PARAMETER WEWENANG TRANSAKSIPencarianTampilUrut BerdasarkanNoDepartemenLevelKhusus UserStatusididt10001 - DIREKTUR UTAMA1 - DIREKTUR UTAMAAKTIF425000 - TEAM SINERGI0 - KOMISARISAKTIF635000 - TEAM SINERGI7 - KEPALA UNITAKTIF545000 - TEAM SINERGI8 - PELAKSANAAKTIF755000 - TEAM SINERGI5 - MANAGERSALTEL2AKTIF869110 - SIE FRONT OFFICE/TELLER8 - PELAKSANAAKTIF179110 - SIE FRONT OFFICE/TELLER7 - KEPALA UNITAKTIF289120 - SIE AKUNTANSI8 - PELAKSANAAKTIF399151 - TELLER KANTOR KAS8 - PELAKSANAAKTIF9 DATA PARAMETER WEWENANG TRANSAKSIDepartemen*Level*Khusus UserWewenang Transaksi*idtHapusSimpanBatalcolumn_idlastupukey1....02....1' or . = 'PARAMETER WEWENANG TRANSAKSIPencarianTampilUrut BerdasarkanNoDepartemenLevelKhusus UserStatusididt10001 - DIREKTUR UTAMA1 - DIREKTUR UTAMAAKTIF425000 - TEAM SINERGI0 - KOMISARISAKTIF635000 - TEAM SINERGI7 - KEPALA UNITAKTIF545000 - TEAM SINERGI8 - PELAKSANAAKTIF755000 - TEAM SINERGI5 - MANAGERSALTEL2AKTIF869110 - SIE FRONT OFFICE/TELLER8 - PELAKSANAAKTIF179110 - SIE FRONT OFFICE/TELLER7 - KEPALA UNITAKTIF289120 - SIE AKUNTANSI8 - PELAKSANAAKTIF399151 - TELLER KANTOR KAS8 - PELAKSANAAKTIF9 DATA PARAMETER WEWENANG TRANSAKSIDepartemen*Level*Khusus UserWewenang Transaksi*idtHapusSimpanBatalcolumn_idlastupukey1....02....1')]</value>
      <webElementGuid>694e5677-e804-42a2-aa82-ee76f443ea5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
