<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_idt_xui.UI.TreeGrid-CELLCAPTIONi-c_b</name>
   <tag></tag>
   <elementGuidId>7d26d685-71f7-4ee4-855a-9bcb5e37b9f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.TreeGrid-CELLCAPTION:i:-c_b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7140df9b-d35c-485e-b1a4-ec2daa7a6dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-CELLCAPTION:i:-c_b</value>
      <webElementGuid>b298d282-9943-4914-af32-eee01d898ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-treegrid-cellcaption xui-v-node     xui-custom</value>
      <webElementGuid>0f43656d-1944-49c8-9ca0-2ca911e0cd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0001 - DIREKTUR UTAMA</value>
      <webElementGuid>c4757bff-fa33-47fe-9a0b-9bdf077fb7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-CELLCAPTION:i:-c_b&quot;)</value>
      <webElementGuid>bbd8eca4-c8c2-4ea7-90bb-6ed156f77806</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-CELLCAPTION:i:-c_b']</value>
      <webElementGuid>ca957ade-205b-4e3f-9ceb-80e6f52bd6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-CELLA:i:-c_b']/span</value>
      <webElementGuid>a30ebad8-90f3-489f-991f-d13203f4b446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='idt'])[1]/following::span[81]</value>
      <webElementGuid>14c2896e-70aa-4eb3-831e-e11334cb6555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='id'])[7]/following::span[85]</value>
      <webElementGuid>a0533d8a-d0d7-4b8b-bcf7-54e65d7e0cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKTIF'])[1]/preceding::span[7]</value>
      <webElementGuid>253b8bd1-a36d-4493-9f52-25bb4f88e58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKTIF'])[2]/preceding::span[31]</value>
      <webElementGuid>0af6b373-be2d-400e-98d1-5e1926184178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0001 - DIREKTUR UTAMA']/parent::*</value>
      <webElementGuid>b1f36555-3c5f-4c61-a77a-78739e6d73c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/div/span[2]/span/span</value>
      <webElementGuid>13d5a16b-72de-4331-b3da-1f53b2915ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.TreeGrid-CELLCAPTION:i:-c_b' and (text() = '0001 - DIREKTUR UTAMA' or . = '0001 - DIREKTUR UTAMA')]</value>
      <webElementGuid>14459a85-2602-455b-b50a-c0bd21f2872b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
