<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_c_xui.UI.Dialog-CAPTIONi</name>
   <tag></tag>
   <elementGuidId>f9afebf7-8a73-4827-b8df-536e2b26374d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.Dialog-CAPTION:i:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c99c3bff-813e-4449-a40a-43ac80fc7983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1a43ac4e-ca7b-451f-baf0-85c79453cf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Dialog-CAPTION:i:</value>
      <webElementGuid>7c107fb1-0586-48d4-a65d-7124088af9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-dialog-caption xui-title-node     xui-custom</value>
      <webElementGuid>ceb8f4f5-1e7a-46af-9842-7fbab1a532ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRANSAKSI UMUM</value>
      <webElementGuid>331e3d3d-41ba-42b7-a23b-0be9bc7d63ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Dialog-CAPTION:i:&quot;)</value>
      <webElementGuid>8b585543-4ddf-4f48-9dd8-d7bf2a35fb39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Dialog-CAPTION:i:']</value>
      <webElementGuid>a63c5353-4f60-4cfe-93e8-caf32387f9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Dialog-BARCMDL:i:']/span[4]</value>
      <webElementGuid>8870a055-e98b-44c3-8af2-3b66f4616830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='c'])[1]/following::span[20]</value>
      <webElementGuid>108adf4f-604e-425a-abac-77fcde86eb41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::span[23]</value>
      <webElementGuid>87bfb8e8-b753-45a9-82f6-afd327d28cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='id'])[1]/preceding::span[14]</value>
      <webElementGuid>7767b397-d0a4-4174-8507-b18b9e2559ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Transaksi*'])[1]/preceding::span[21]</value>
      <webElementGuid>59f3fe2a-8366-427b-b071-9641ec5401fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TRANSAKSI UMUM']/parent::*</value>
      <webElementGuid>492bd2d9-e5ad-4648-ab3f-380577d2e5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/div/div/span[4]</value>
      <webElementGuid>d5a8fa17-44c2-48e4-9791-5edea7f23f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.Dialog-CAPTION:i:' and (text() = 'TRANSAKSI UMUM' or . = 'TRANSAKSI UMUM')]</value>
      <webElementGuid>00bc6314-907d-432a-97f1-08fc8d494e3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
