<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_idt_xui.UI.TreeGrid-CMDi-r_a_edit</name>
   <tag></tag>
   <elementGuidId>c4ed542f-58a9-412a-84c0-b8592fd0f1ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xui.UI.TreeGrid-CMD:i:-r_a_edit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>249721de-9b9e-4fcf-8681-40f6fa110f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>e7f92962-b9a0-4f24-85c8-e6797689859f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f0ee030f-1a2a-454e-8b03-01374b4ae917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-CMD:i:-r_a_edit</value>
      <webElementGuid>c9007998-0d75-4dc2-82dd-99c1fb5655c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-image xui-node-image-hover xui-treegrid-cmd xui-treegrid-cmd-hover xui-node xui-node-hover xui-tag-cmd xui-tag-cmd-hover fa fa-hover fa-lg fa-lg-hover fa-edit fa-edit-hover xui-custom xui-custom-hover</value>
      <webElementGuid>a0f96e26-fb22-498e-99c1-bf3e556a63dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-CMD:i:-r_a_edit&quot;)</value>
      <webElementGuid>912b18f6-139c-435e-912e-55f4e930c569</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xui.UI.TreeGrid-CMD:i:-r_a_edit']</value>
      <webElementGuid>7e13fe4b-50d5-4bf6-83be-d8cffaa57f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-LTAGCMDS:i:-r_a']/img</value>
      <webElementGuid>bfe3ff05-4013-48d0-bba7-b2b667a86f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Ubah']</value>
      <webElementGuid>f1fddb05-1e28-4b26-b2a2-94b1297a903f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/img</value>
      <webElementGuid>732bb0b6-9406-466a-baf6-8d46be3290b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Ubah' and @id = 'xui.UI.TreeGrid-CMD:i:-r_a_edit']</value>
      <webElementGuid>03ff662a-ea99-4ff8-8c14-6cbabd7157f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
