<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_correction_xui.UI.TreeGrid-CMDa-r_c_edit</name>
   <tag></tag>
   <elementGuidId>28abd10f-f7c2-409d-bdf6-b0ea00101513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xui.UI.TreeGrid-CMD:a:-r_c_edit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a3019d4f-8e39-4c0d-b083-6d157498324a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>dc411395-2141-4ed6-8e53-7d63d8de05dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7271d6bc-7b42-457b-898c-b4c5610f65d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-CMD:a:-r_c_edit</value>
      <webElementGuid>3c248326-c7e4-49bd-8ae9-1ed8d7d31058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-image xui-node-image-hover xui-treegrid-cmd xui-treegrid-cmd-hover xui-node xui-node-hover xui-tag-cmd xui-tag-cmd-hover fa fa-hover fa-lg fa-lg-hover fa-edit fa-edit-hover xui-custom xui-custom-hover</value>
      <webElementGuid>c01f70d7-ff26-45ef-bfea-066c7158ae25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-CMD:a:-r_c_edit&quot;)</value>
      <webElementGuid>edf7cab7-d5ad-4b84-8e4b-2e44b3823f37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xui.UI.TreeGrid-CMD:a:-r_c_edit']</value>
      <webElementGuid>32af8710-8043-422e-80ee-52477eaed785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-LTAGCMDS:a:-r_c']/img</value>
      <webElementGuid>e4897139-2222-43ed-ad6f-7eefc0b260f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Ubah'])[3]</value>
      <webElementGuid>4c7a37a8-09cd-4d19-abf1-f9554926e63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/span/span[2]/img</value>
      <webElementGuid>808a6215-f3db-4425-a74a-dfc0850757da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Ubah' and @id = 'xui.UI.TreeGrid-CMD:a:-r_c_edit']</value>
      <webElementGuid>8cdff086-e942-4800-8e33-156476bfa2ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
