<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_O K (1)</name>
   <tag></tag>
   <elementGuidId>210fc260-00c7-4cdc-a357-2feea5205745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='xlid'])[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;O K&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>50b15f6d-900f-4813-9b7c-6c179d2c3bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xlid</value>
      <webElementGuid>837b811f-8bfc-4c11-b484-ffe3e78c03b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline.ok</value>
      <webElementGuid>b3fd19e4-5630-480f-8873-51d9bccd6ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>O K</value>
      <webElementGuid>71358d2b-b9a0-4626-98d3-fded73579ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Button-CAPTION:af:&quot;)/span[@id=&quot;xlid&quot;]</value>
      <webElementGuid>6189601e-d94d-408c-b555-93a38a2a4077</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='xlid'])[20]</value>
      <webElementGuid>985ee3e1-68e3-4fa7-9141-54406bc4b950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Button-CAPTION:af:']/span</value>
      <webElementGuid>06287057-5278-4c78-92a3-03a2d72dbc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INFORMASI'])[2]/following::span[13]</value>
      <webElementGuid>5c29c1d2-e216-46f4-a92e-787bacb4202a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From: USER'])[1]/following::span[27]</value>
      <webElementGuid>e4d0cbef-cfb9-48b4-a960-1763c2eba699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[SC0006] Berhasil tolak data.'])[1]/preceding::span[2]</value>
      <webElementGuid>ed115c26-0ce5-4239-b777-e8563419803d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Favorite'])[1]/preceding::span[11]</value>
      <webElementGuid>24abb1e3-2788-4a62-9da7-685aab5aabbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='O K']/parent::*</value>
      <webElementGuid>b2a8e380-117f-4f6c-9fe4-c3759b2f9dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]/span</value>
      <webElementGuid>73721e2f-9158-4332-a3f8-8d0d34d0bb06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xlid' and (text() = 'O K' or . = 'O K')]</value>
      <webElementGuid>c541130e-ac7c-4651-9a77-d603c049acda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
