<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1. Copy URL berikut dan paste di Tab Br_6170e0</name>
   <tag></tag>
   <elementGuidId>d935665a-257b-4d1c-89a5-0ba30e0d3fb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:u:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1. Copy URL berikut dan paste di Tab Browser baru: chrome://flags/#enable-webrtc&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d18eb540-44ea-46fc-8cd4-8b8c002f40b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>18724d2d-030e-4126-af0a-c0a2c3815044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Div:u:</value>
      <webElementGuid>9ceed3b4-25d1-44a6-b73b-8e018135f9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-div xui-uicontainer  xui-ui-ctrl xui-ui-selectable      xui-custom</value>
      <webElementGuid>5cd3fef2-e8ad-4d63-a452-fc7136b9a118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)</value>
      <webElementGuid>941f31c6-85ea-4a93-b3a0-5360706c3f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:u:&quot;)</value>
      <webElementGuid>c6e28a65-59d2-4052-a0ba-ebcf1478bcba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:u:']</value>
      <webElementGuid>77d9300e-0d06-4f24-a264-c6e6b25fcebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Dialog-PANEL:h:']/div[2]</value>
      <webElementGuid>5c29559c-47e0-48ce-8743-099f2aab55f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O K'])[2]/following::div[1]</value>
      <webElementGuid>6adf9d35-6bbb-4fe2-a410-56347e62f810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IP Tidak Terdeteksi'])[1]/following::div[8]</value>
      <webElementGuid>2dd578cf-9293-4068-8800-2638f3725356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1. Copy URL berikut dan paste di Tab Browser baru:']/parent::*</value>
      <webElementGuid>bb7516c1-8723-4433-92a2-7e09bdee8597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[17]/span/span/div[2]/div/div/div[2]</value>
      <webElementGuid>09fab940-344c-4bce-bf4c-6d9ff6d311b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Div:u:' and (text() = '1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)' or . = '1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)')]</value>
      <webElementGuid>48c52ae7-0311-4f8f-bd09-d240e7742929</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
