<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_O K_xui.UI.Divu (2)</name>
   <tag></tag>
   <elementGuidId>aaa42a00-a78c-496f-8651-7c62e9bfcc8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:u:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c09ba7e-aab6-4206-ab87-19351994ca65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4ae24ece-eb4b-4d57-97a6-6c01bdcee397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Div:u:</value>
      <webElementGuid>d71c23e5-3bb3-43aa-8e93-dd270b8c09f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-div xui-uicontainer  xui-ui-ctrl xui-ui-selectable      xui-custom</value>
      <webElementGuid>d008b6d6-ad8e-4698-97a2-bd0b2d5899e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)</value>
      <webElementGuid>5a8a20c9-88ee-406c-84b0-45524d527155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:u:&quot;)</value>
      <webElementGuid>c72ce03f-e6ef-4fc4-84ec-f5ca9a024a11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:u:']</value>
      <webElementGuid>b6f836a7-b4de-4cb4-8a40-cbef3b0cc120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Dialog-PANEL:h:']/div[2]</value>
      <webElementGuid>3890ec7f-e9ed-4b67-8483-b5fd9a627210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O K'])[2]/following::div[1]</value>
      <webElementGuid>35287779-7bcd-41c0-ba28-e6189112b254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IP Tidak Terdeteksi'])[1]/following::div[8]</value>
      <webElementGuid>803dbd4c-b96b-498a-bc63-aecb4ec89c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1. Copy URL berikut dan paste di Tab Browser baru:']/parent::*</value>
      <webElementGuid>be2ea182-e0d7-4c08-a9e9-a7c1262d93a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[17]/span/span/div[2]/div/div/div[2]</value>
      <webElementGuid>29574d65-082b-4560-af00-a7068281a794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Div:u:' and (text() = '1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)' or . = '1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)')]</value>
      <webElementGuid>f69d0b2f-b0e9-487a-ace4-84c68cd45e51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
