<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilihan Printer_xui.UI.StatusButtons-C_8187c0</name>
   <tag></tag>
   <elementGuidId>d35f2ae1-035d-42f9-bf77-09434d063974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.StatusButtons-CAPTION:a:a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>48650939-51e2-4838-a638-2a86994cacfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.StatusButtons-CAPTION:a:a</value>
      <webElementGuid>bf1cdd6c-d9d6-41c0-9aa7-f7fd1b1bd077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-statusbuttons-caption     xui-custom</value>
      <webElementGuid>8f3b52be-193e-4e89-82cd-84ef3b71d22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tidak</value>
      <webElementGuid>9774cda4-692a-4209-ae45-09d02f7a947d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.StatusButtons-CAPTION:a:a&quot;)</value>
      <webElementGuid>856db145-0a01-4fa6-9ac0-4d4b37d6b977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.StatusButtons-CAPTION:a:a']</value>
      <webElementGuid>fd053df2-602a-4cfc-b86a-f47f61207090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.StatusButtons-ITEM:a:a']/span[3]</value>
      <webElementGuid>04fa8117-756a-48b4-b6d8-70775aaff4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilihan Printer'])[1]/following::span[9]</value>
      <webElementGuid>195b0a85-a33c-40dc-bbf6-81aa56b7382d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak Validasi ?'])[1]/following::span[15]</value>
      <webElementGuid>453c6043-2a93-42b9-b90e-fe82943ed1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak'])[1]/preceding::span[6]</value>
      <webElementGuid>9c1a5968-ff4a-4620-a127-8eeedf7f9c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::span[13]</value>
      <webElementGuid>dae51577-23b4-416f-827e-9cd85f28c2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tidak']/parent::*</value>
      <webElementGuid>fcf27f36-3025-4972-9484-42c2c6931cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/span/span[3]</value>
      <webElementGuid>339e0ab4-b012-4c59-97d6-e2c6fb7c8522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.StatusButtons-CAPTION:a:a' and (text() = 'Tidak' or . = 'Tidak')]</value>
      <webElementGuid>5b3ecd37-8a4b-4ab7-a51b-d2273eeeb3f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
